//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLP.AutoConnector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class AutoConnector : global::System.Configuration.ApplicationSettingsBase {
        
        private static AutoConnector defaultInstance = ((AutoConnector)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AutoConnector())));
        
        public static AutoConnector Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://docs.google.com/document/d/1kTyZXmp8l5TWeQYctaFE5X4D_rw-SHAClW8Ahx5g1lY/e" +
            "dit?tab=t.sshawpz9zd4z")]
        public string ConnectRailingsHelpURL {
            get {
                return ((string)(this["ConnectRailingsHelpURL"]));
            }
            set {
                this["ConnectRailingsHelpURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://docs.google.com/document/d/1kTyZXmp8l5TWeQYctaFE5X4D_rw-SHAClW8Ahx5g1lY/e" +
            "dit?tab=t.xzypimv1eci7#heading=h.y18n6vjhoxd5")]
        public string DisconnectRailingsHelpURL {
            get {
                return ((string)(this["DisconnectRailingsHelpURL"]));
            }
            set {
                this["DisconnectRailingsHelpURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://docs.google.com/document/d/1kTyZXmp8l5TWeQYctaFE5X4D_rw-SHAClW8Ahx5g1lY/e" +
            "dit?tab=t.vku41tjbv71v#heading=h.38xcujhq4ut")]
        public string JoinCICapsAndHostHelpURL {
            get {
                return ((string)(this["JoinCICapsAndHostHelpURL"]));
            }
            set {
                this["JoinCICapsAndHostHelpURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://docs.google.com/document/d/1kTyZXmp8l5TWeQYctaFE5X4D_rw-SHAClW8Ahx5g1lY/e" +
            "dit?tab=t.0#heading=h.uck0vjjgkal7")]
        public string AutoConnectorHelpURL {
            get {
                return ((string)(this["AutoConnectorHelpURL"]));
            }
            set {
                this["AutoConnectorHelpURL"] = value;
            }
        }
    }
}
