//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLP.AutoConnector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.6.0.0")]
    internal sealed partial class ConnectRailings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConnectRailings defaultInstance = ((ConnectRailings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConnectRailings())));
        
        public static ConnectRailings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UpperRailingConnectionX_0 {
            get {
                return ((double)(this["UpperRailingConnectionX_0"]));
            }
            set {
                this["UpperRailingConnectionX_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UpperRailingConnectionDZ_0 {
            get {
                return ((double)(this["UpperRailingConnectionDZ_0"]));
            }
            set {
                this["UpperRailingConnectionDZ_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LowerRailingConnectionDZ_0 {
            get {
                return ((double)(this["LowerRailingConnectionDZ_0"]));
            }
            set {
                this["LowerRailingConnectionDZ_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RailingsConnectionType {
            get {
                return ((int)(this["RailingsConnectionType"]));
            }
            set {
                this["RailingsConnectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectAnymore {
            get {
                return ((bool)(this["SelectAnymore"]));
            }
            set {
                this["SelectAnymore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectAnymoreWithDialog {
            get {
                return ((bool)(this["SelectAnymoreWithDialog"]));
            }
            set {
                this["SelectAnymoreWithDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HandrailToConnect {
            get {
                return ((int)(this["HandrailToConnect"]));
            }
            set {
                this["HandrailToConnect"] = value;
            }
        }
    }
}
