//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLP.AutoConnector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class InputData : global::System.Configuration.ApplicationSettingsBase {
        
        private static InputData defaultInstance = ((InputData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InputData())));
        
        public static InputData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RailingConnectionAlignX {
            get {
                return ((double)(this["RailingConnectionAlignX"]));
            }
            set {
                this["RailingConnectionAlignX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double CrossoverSolidX {
            get {
                return ((double)(this["CrossoverSolidX"]));
            }
            set {
                this["CrossoverSolidX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public double CrossoverSolidZ {
            get {
                return ((double)(this["CrossoverSolidZ"]));
            }
            set {
                this["CrossoverSolidZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public double CrossoverSolidY {
            get {
                return ((double)(this["CrossoverSolidY"]));
            }
            set {
                this["CrossoverSolidY"] = value;
            }
        }
    }
}
