//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLP.AutoConnector.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FailureMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FailureMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLP.AutoConnector.Resources.FailureMessages", typeof(FailureMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось присоединить бетонные заглушки к основе.
        /// </summary>
        internal static string CannotJoinCICapsAndHost {
            get {
                return ResourceManager.GetString("CannotJoinCICapsAndHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найден параметр материала для бетонных заглушек.
        /// </summary>
        internal static string ConcreteCapMaterialParameterNotFound {
            get {
                return ResourceManager.GetString("ConcreteCapMaterialParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдены заглушки в закладных деталях, имя семейства не содержит:.
        /// </summary>
        internal static string ConcreteCapsNotFound {
            get {
                return ResourceManager.GetString("ConcreteCapsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Различные диаметры поручней ограждений.
        /// </summary>
        internal static string HandrailDiametersAreDifferent {
            get {
                return ResourceManager.GetString("HandrailDiametersAreDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На поручне вместе стыка включена заглушка - следует отредактировать тип ограждения.
        /// </summary>
        internal static string HandrailEndCapIsEnabled {
            get {
                return ResourceManager.GetString("HandrailEndCapIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Материал основы закладной детали не является бетоном, имя материала не содержит:.
        /// </summary>
        internal static string HostMaterialIsNotConcrete {
            get {
                return ResourceManager.GetString("HostMaterialIsNotConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдена основа закладной детали.
        /// </summary>
        internal static string HostNotFound {
            get {
                return ResourceManager.GetString("HostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный ввод значений.
        /// </summary>
        internal static string IncoorectInputValue {
            get {
                return ResourceManager.GetString("IncoorectInputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получено недопустимое отрицательное значение параметра привязки крайней опоры к краю поручня.
        /// </summary>
        internal static string NegativeEdgeSupportAlign {
            get {
                return ResourceManager.GetString("NegativeEdgeSupportAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружены заглушки на стыкуемых участках поручней ограждений. Необходимо отредактировать соответствующие параметры типа.
        /// </summary>
        internal static string RailingCapsTurnedOn {
            get {
                return ResourceManager.GetString("RailingCapsTurnedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Семейство ограждения не поддерживается, имя семейства: .
        /// </summary>
        internal static string RailingFamilyNotSupported {
            get {
                return ResourceManager.GetString("RailingFamilyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограждения не параллельны друг другу.
        /// </summary>
        internal static string RailingsNotParallel {
            get {
                return ResourceManager.GetString("RailingsNotParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограждения расположены слишком близко друг к другу, минимальное расстояние: .
        /// </summary>
        internal static string RailingsTooClose {
            get {
                return ResourceManager.GetString("RailingsTooClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная ошибка.
        /// </summary>
        internal static string UnknowFailure {
            get {
                return ResourceManager.GetString("UnknowFailure", resourceCulture);
            }
        }
    }
}
